### ISSUE TITLE
Incorrect z-points when loading .bts file (.wnd OK)

### ISSUE THREAD

**Issue by jennirinker** [lkilcher/pyTurbSim#4]
When using pyts.io to load in a TurbSim output file, the grid for the .bts file seems to be incorrect. Here is a verification plot from a .wnd file, which shows the correct grid ordering (the velocity profile is the top left plot):

![5pts_nosc_ts](https://cloud.githubusercontent.com/assets/11503804/7006953/900253ec-dc42-11e4-8872-ff0ef1f70bb3.png)

The values for z in tsout.grid.z for this file are [20,55,90,125,160], as it should be for a 5-point, 140-m grid centered at 90 m.

Here is the exact same plot, but loading the .bts file instead. The velocity profile now seems to be reversed, as is the turbulence intensity profile just below it.

![5pts_nosc_ts_bts](https://cloud.githubusercontent.com/assets/11503804/7006954/9017a742-dc42-11e4-9372-cdf7fd0fe584.png)

The values for z in tsout.grid.z for this file are now [37.5,72.5,107.5,142.5,177.5], which is not correct. Additionally, the order in which the points were stored in the turbulence structure seem to be backwards. Both files were generated from the same TurbSim input file and run.

**Comment by lkilcher** [comment]
I just made an attempt to fix this here: 5d0a5d148fc9e188940bd5146f11137ce6056b35. Can you grab those changes and confirm that they fix the issue? Also, can you confirm that read/write of PyTS output to/from .bts files is symmetric (same data before read/write as after)?

**Comment by lkilcher** [comment]
Jenni, I've committed these changes to the master branch. Can you confirm that this issue is in fact resolved? Thanks!

**Comment by jennirinker** [comment]
Hey Levi!

I tried to upgrade my version of PyTurbSim and got an error on compiling
"fortranobject". I tried uninstalling and reinstalling, the same error
comes up. I attached a pip log so you can see what's going on. PyTurbSim
still seems to run, though it is again throwing the warning that tslib did
not load properly. Sadly, I forgot how to recompile tslib on windows.
Whoops.

Anyway, since PyTurbSim seemed to be installed (I could import pyts.main
from the command line, so it seems okay except for the tslib issue), I
tried to load the bts to see if the issue is resolved. After dicking around
a bit, I realized it's not the z-grid points that differ when loading .wnd
and .bts files, it's how the points are ordered within tsout.u. To be
specific, the .wnd file orders the grid points where the first row is the
lowest height and the last row is the highest height. The bts file orders
the points where the first row is the highest points and the last row is
the lowest. The vector stored in tsout.grid.z seems to be the same
regardless of bts or wnd types.

I've attached a bts and wnd file so you can see what I mean. The snippet of
code below should make the differences between the two clear.

Jenni

======================================================
import pyts.io.main as io

# filenames
wnd_fname = '5pts_Usr.wnd'
bts_fname = '5pts_Usr.bts'

# load modules
wnd_tsout = io.readModel(wnd_fname)
bts_tsout = io.readModel(bts_fname)

# get z-vectors
wnd_z = wnd_tsout.grid.z
bts_z = bts_tsout.grid.z

print('wnd_z: ', wnd_z)
print('bts_z: ', bts_z)

# get grid arrays
wnd_u = wnd_tsout.u
bts_u = bts_tsout.u

# print means of arrays
print(np.mean(wnd_u,axis=2))
print(np.mean(bts_u,axis=2))
======================================================
