### ISSUE TITLE
Incorrect grid center in pyts.io.read: turbsim()

### ISSUE THREAD

**Issue by jennirinker** [lkilcher/pyTurbSim#5]
Line 116 in the <turbsim> function in pyts.io.read defines the grid center as
    center = z0 + n_z  * dz / 2.0.

However, the grid center should actually be defined according to
    center = z0 + (n_z - 1) * dz / 2.0

For example, an 11-point grid with z_0 = 0.0 and dz = 10.0 (i.e., a grid ranging from 0.0 to 100.0) should have the center point at 50.0, but the original calculation will have the center at 55.0 m.

**Comment by lkilcher** [comment]
Resolved by 3a94a9fb79298d4bd24904a7d5080e4e2c17d40a.
